# Generated by Django 3.1.4 on 2021-01-04 11:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_parser', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='vacancy_link',
            new_name='link',
        ),
        migrations.RemoveField(
            model_name='job',
            name='post_date',
        ),
        migrations.AddField(
            model_name='job',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 1, 4, 14, 39, 36, 613046)),
        ),
    ]
